spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  datasource:
    url: jdbc:h2:~/testdb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          discord:
            clientId: ${DDB_CLIENT_ID}
            clientSecret: ${DDB_CLIENT_SECRET}
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope: identify
        provider:
          discord:
            authorizationUri: https://discord.com/api/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token


