spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:file:./testdb
    username: user
    password: pass
    driver-class-name: org.h2.Driver
  security:
    oauth2:
      client:
        registration:
          discord:
            clientId: ${DDB_CLIENT_ID}
            clientSecret: ${DDB_CLIENT_SECRET}
            authorizationGrantType: authorization_code
            redirectUri: "{baseUrl}/login/oauth2/code/discord"
            scope: identify,applications.commands.permissions.update
        provider:
          discord:
            authorizationUri: https://discord.com/api/oauth2/authorize
            tokenUri: https://discord.com/api/oauth2/token


